# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_repos:
- branch: master
  name: pulp_file
- branch: master
  name: pulp_container
- branch: master
  name: pulp_rpm
- branch: main
  name: pulp_deb
black: false
check_commit_message: true
check_gettext: true
check_manifest: true
check_openapi_schema: true
check_stray_pulpcore_imports: false
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: false
issue_tracker: redmine
plugin_app_label: pulp_2to3_migration
plugin_camel: Pulp-2To3-Migration
plugin_camel_short: 2To3-Migration
plugin_caps: PULP-2TO3-MIGRATION
plugin_caps_short: 2TO3-MIGRATION
plugin_dash: pulp-2to3-migration
plugin_dash_short: 2to3-migration
plugin_default_branch: master
plugin_name: pulp-2to3-migration
plugin_snake: pulp_2to3_migration
publish_docs_to_pulpprojectdotorg: true
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: null
pydocstyle: false
pypi_username: pulp
redmine_project: migration
release_user: pulpbot
test_bindings: false
test_cli: true
test_performance: false
test_released_plugin_with_next_pulpcore_release: false
test_s3: false
travis_addtl_services:
- mongodb
travis_notifications:
  irc:
    channels:
    - chat.freenode.net#pulp-build
    on_failure: always
    on_success: change
update_redmine: true
upgrade_range: []

